sudo: true
dist: trusty
language: scala
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - /^\d\.\d+$/
scala:
  - 2.12.8
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"

# These directories are cached to S3 at the end of the build
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

stages:
  - test
  - name: release
    if: tag =~ ^v
  - name: snapshot
    if: (NOT tag IS present) AND (type = push)
jobs:
  include:
    - stage: test
      script: sbt coverage test && sbt coverageReport coveralls
    - stage: release
      script: sbt publishSigned sonatypeBundleRelease
    - stage: snapshot
      script: sbt publish
